"""empty message

Revision ID: 7aac5cb84da5
Revises: 5eadcc533da2
Create Date: 2024-09-11 22:47:11.969869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7aac5cb84da5'
down_revision = '5eadcc533da2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assistantsfiles', schema=None) as batch_op:
        batch_op.alter_column('file_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assistantsfiles', schema=None) as batch_op:
        batch_op.alter_column('file_id',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
