"""empty message

Revision ID: fa27faeea636
Revises: 7aac5cb84da5
Create Date: 2024-09-17 12:53:51.914715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa27faeea636'
down_revision = '7aac5cb84da5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assistantsfiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assistantsfiles', schema=None) as batch_op:
        batch_op.drop_column('active')

    # ### end Alembic commands ###
